import { Check, HelpCircle } from 'lucide-react';
import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import SectionHeading from '@/components/ui/SectionHeading';
import { fetchMembershipPlans } from '@/redux/slices/membershipPlanSlice';
import { formatCurrency } from '@/utils/formatters';

export default function Membership() {
  const dispatch = useDispatch();
  const plans = useSelector((state) => state.membershipPlans.items);
  useEffect(() => { dispatch(fetchMembershipPlans()); }, [dispatch]);
  return <div><section className="bg-ink-950 pb-20 pt-36 text-white"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-400">Memberships</p><h1 className="mt-5 max-w-3xl font-display text-5xl font-bold tracking-[-.04em] sm:text-6xl">Choose the plan<br /><span className="text-brand-400">that fits your life.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-surface-300">Every membership includes full access to our training floor and the freedom to build your routine your way.</p></div></section><section className="py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionHeading eyebrow="Simple by design" title="Your training, your terms." description="No confusing tiers. Just clear options built around how you want to train." /><div className="mt-12 grid gap-6 lg:grid-cols-3">{plans.map((plan, index) => <Card key={plan.id} className={`relative ${index === 1 ? 'border-brand-500 shadow-xl shadow-brand-500/10' : ''}`}>{index === 1 && <span className="absolute right-6 top-6 rounded-full bg-brand-500 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">Most popular</span>}<div className="flex h-12 w-12 items-center justify-center rounded-xl bg-brand-100 font-display font-bold text-brand-700 dark:bg-brand-500/10 dark:text-brand-400">0{index + 1}</div><h3 className="mt-7 font-display text-2xl font-bold text-ink-950 dark:text-white">{plan.name}</h3><p className="mt-2 min-h-12 text-sm leading-6 text-surface-500">{plan.description}</p><div className="mt-7 border-y border-surface-200 py-5 dark:border-surface-800"><span className="font-display text-4xl font-bold text-ink-950 dark:text-white">{formatCurrency(plan.price)}</span><span className="ml-2 text-sm text-surface-500">for {plan.duration_days} days</span></div><ul className="mt-6 space-y-3">{(plan.features || []).map((feature) => <li key={feature} className="flex gap-2 text-sm text-surface-600 dark:text-surface-300"><Check size={16} className="mt-0.5 shrink-0 text-brand-500" />{feature}</li>)}</ul><Link to="/register"><Button variant={index === 1 ? 'primary' : 'secondary'} className="mt-8 w-full">Choose {plan.name}</Button></Link></Card>)}</div><div className="mt-16 rounded-2xl border border-surface-200 bg-surface-50 p-6 dark:border-surface-800 dark:bg-surface-900"><div className="flex gap-4"><HelpCircle className="shrink-0 text-brand-600" /><div><p className="font-semibold text-ink-900 dark:text-white">Need help choosing?</p><p className="mt-1 text-sm text-surface-600 dark:text-surface-400">Start with Basic and upgrade whenever your routine grows. Your consistency matters more than the plan you choose.</p></div></div></div></div></section></div>;
}
